CREATE ROLE idel_app LOGIN PASSWORD 'idel_local_only' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE idel_auth LOGIN PASSWORD 'idel_auth_local_only' NOSUPERUSER NOCREATEDB NOCREATEROLE BYPASSRLS;
GRANT CONNECT ON DATABASE idel_os TO idel_app;
GRANT CONNECT ON DATABASE idel_os TO idel_auth;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
