import { boolean, date, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

import { organizations, users } from "./core.js";
import { adminTaskStatusEnum, documentSourceEnum, invoiceStatusEnum } from "./enums.js";
import { patients } from "./patients.js";
import { tours } from "./tours.js";

export const adminTasks = pgTable("admin_tasks", {
  id: uuid("id").defaultRandom().primaryKey(),
  orgId: uuid("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  type: text("type").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  dueDate: date("due_date"),
  priority: integer("priority").notNull(),
  relatedResourceType: text("related_resource_type"),
  relatedResourceId: uuid("related_resource_id"),
  status: adminTaskStatusEnum("status").default("open").notNull(),
  autoGenerated: boolean("auto_generated").default(false).notNull(),
  ruleKey: text("rule_key"),
});

export const documents = pgTable("documents", {
  id: uuid("id").defaultRandom().primaryKey(),
  orgId: uuid("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  patientId: uuid("patient_id").references(() => patients.id),
  type: text("type").notNull(),
  name: text("name").notNull(),
  fileUrl: text("file_url").notNull(),
  expiresAt: date("expires_at"),
  uploadedBy: uuid("uploaded_by").notNull().references(() => users.id),
});

export const invoicesMirror = pgTable("invoices_mirror", {
  id: uuid("id").defaultRandom().primaryKey(),
  orgId: uuid("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  patientId: uuid("patient_id").notNull().references(() => patients.id),
  visitId: uuid("visit_id"),
  externalRef: text("external_ref"),
  amountCents: integer("amount_cents").notNull(),
  status: invoiceStatusEnum("status").notNull(),
  rejectedReasonCode: text("rejected_reason_code"),
  rejectedAt: timestamp("rejected_at", { withTimezone: true }),
  source: documentSourceEnum("source").notNull(),
});

export const mileageLogs = pgTable("mileage_logs", {
  id: uuid("id").defaultRandom().primaryKey(),
  orgId: uuid("org_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
  userId: uuid("user_id").notNull().references(() => users.id),
  date: date("date").notNull(),
  distanceKm: integer("distance_km").notNull(),
  isProfessional: boolean("is_professional").default(true).notNull(),
  tourId: uuid("tour_id").references(() => tours.id),
});
